### ISSUE TITLE
LoRa Print Statement Confusion

### ISSUE THREAD

**Issue by BGoto808** [OPEnSLab-OSU/Loom#138]
**Is your feature request related to a problem? Please describe.**
The LoRa transfer code prints a confusing error that may mislead users that something is going wrong. The wording is "LoRa: Receive Failed" which can be interpreted that the communication between the two devices is going wrong when that might not actually be the case. For example, the communication could've gone through if the hub was given more time to receive the data, but misinterpreted that the LoRa communication is bad.

**Describe the solution you'd like**
Change the print statement "LoRa: Receive Failed" to something more general to avoid confusion.

**Comment by MrKangs** [comment]
I believe that if you want to see the exact details about where the error came from, you need to turn on the print_verbosity to high, which is 2 in the general settings. For example, the bold part should be added in the JSON file below to see any issues with any modules themselves. It will be annoying to see all the modules information, but it is properly the best way to know more detail about the issues. At the same time, even when you turned on the verbosity, these messages do not tell the exact error in-depth as you are looking for. Therefore, when I was working on a large package size communication between boards, I was also trying to figure out if there is a better way to know the errors, but I found out that there was no way because package lost, for example, could occur on either sending board or receiving board or both which is hard to indicate where it came from. Hence, this is properly the best solution to know the error. Most of them are trial and error until you find a stable communication. I hope that helped.  
`` "{\
	'general':\
	{\
		'name':'Device',\
		'instance':1,\
		'interval':2000,\
                **'print_verbosity':2\**
	},\
	'components':[\
		{\
			'name':'Analog',\
			'params':[\
				8,\
				12,\
				true,\
				true,\
				true,\
				true,\
				true,\
				true,\
				0,\
				0,\
				0,\
				0,\
				0,\
				0\
			]\
		},\
		{\
			'name':'LoRa',\
			'params':[\
				255,\
				0,\
				23,\
				3,\
				200\
			]\
		}\
	]\
}"
``
I am going to close this issue unless there is a better method to solve this issue
