### ISSUE TITLE
Errors from not having all libraries downloaded

### ISSUE THREAD

**Issue by veacha** [OPEnSLab-OSU/Loom#17]
I tried to compile an example and had errors from not having each library downloaded in the IDE on PC. Opened library manager and downloaded each one as they came up. Could there be a list of all libraries needed in order to work with Loom with set-up instructions?

**Comment by Cogswatch** [comment]
Try heading over to the [**Install the Loom Dependencies**](https://github.com/OPEnSLab-OSU/Loom/wiki/Loom-Installation#install-the-loom-dependencies) section on our wiki, which provides details on how to acquire all the library dependencies. We are currently tailoring development towards automating the process rather than expecting users to perform the install manually. Does this help?

**Comment by veacha** [comment]
Yes this helps. Thank you
